#!/bin/bash
# Multi-OS Linux - 低功耗优化内核配置工具
# 兼顾低功耗与高性能的平衡配置

set -e

readonly CONFIG_FILE="config-multi-os-low-power"

cat > "$CONFIG_FILE" << 'EOF'
# Multi-OS Linux 低功耗优化内核配置
CONFIG_LOCALVERSION="-multi-os-low-power"
CONFIG_DEFAULT_HOSTNAME="multi-os"

# ------------------------------
# 低功耗核心设置
# ------------------------------

# 时钟频率 - 250HZ 适合低功耗，响应性也足够
CONFIG_HZ_250=y
CONFIG_HZ=250

# 调度器 - CFS 优化，平衡响应和功耗
CONFIG_SCHED_FAIR=y
CONFIG_SCHED_FAIR_GROUP=y
CONFIG_SCHED_MC=y          # 多核调度优化
CONFIG_SCHED_SMT=y         # SMT 调度优化
CONFIG_NO_HZ=y             # 动态滴答，减少唤醒
CONFIG_NO_HZ_IDLE=y        # 空闲时停止时钟
CONFIG_HIGH_RES_TIMERS=y   # 高精度计时器

# ------------------------------
# 电源管理 (ACPI)
# ------------------------------

CONFIG_ACPI=y
CONFIG_ACPI_AC=y
CONFIG_ACPI_BATTERY=y
CONFIG_ACPI_BUTTON=y
CONFIG_ACPI_CONTAINER=y
CONFIG_ACPI_CPPC_LIB=y
CONFIG_ACPI_DOCK=y
CONFIG_ACPI_FAN=y
CONFIG_ACPI_HOTPLUG_CPU=y
CONFIG_ACPI_IPMI=y
CONFIG_ACPI_NUMA=y
CONFIG_ACPI_PCI_SLOT=y
CONFIG_ACPI_PLATFORM_PROFILE=y
CONFIG_ACPI_PROCESSOR=y
CONFIG_ACPI_PROCESSOR_IDLE=y
CONFIG_ACPI_PCI=y
CONFIG_ACPI_PCI_ROUTER=y
CONFIG_ACPI_SLEEP=y
CONFIG_ACPI_SRAT=y
CONFIG_ACPI_THERMAL=y
CONFIG_ACPI_NFIT=y
CONFIG_ACPI_HMAT=y
CONFIG_ACPI_BGRT=y
CONFIG_ACPI_FPDT=y
CONFIG_ACPI_NBTS=y
CONFIG_ACPI_PCC=y
CONFIG_ACPI_FFH=y
CONFIG_ACPI_PMC=y
CONFIG_ACPI_TAD=y

# ------------------------------
# CPU 电源优化
# ------------------------------

CONFIG_CPU_IDLE=y
CONFIG_CPU_IDLE_GOV_LADDER=y
CONFIG_CPU_IDLE_GOV_MENU=y
CONFIG_CPU_IDLE_GOV_TEO=y
CONFIG_CPU_IDLE_GOV_HALTPOLL=y
CONFIG_CPU_FREQ=y
CONFIG_CPU_FREQ_DEFAULT_GOV_ONDEMAND=y
CONFIG_CPU_FREQ_GOV_PERFORMANCE=y
CONFIG_CPU_FREQ_GOV_POWERSAVE=y
CONFIG_CPU_FREQ_GOV_USERSPACE=y
CONFIG_CPU_FREQ_GOV_ONDEMAND=y
CONFIG_CPU_FREQ_GOV_CONSERVATIVE=y
CONFIG_CPU_FREQ_GOV_SCHEDUTIL=y
CONFIG_X86_ACPI_CPUFREQ=y
CONFIG_X86_INTEL_PSTATE=y
CONFIG_X86_AMD_PSTATE=y
CONFIG_X86_SPEEDSTEP_LIB=y
CONFIG_X86_SPEEDSTEP_CENTRINO=y
CONFIG_X86_POWERNOW_K8=y
CONFIG_X86_PCC_CPUFREQ=y
CONFIG_X86_POWERNOW_K6=y
CONFIG_X86_LONGTERM=y
CONFIG_X86_16BIT=y
CONFIG_X86_CMPXCHG64=y
CONFIG_X86_X2APIC=y

# ------------------------------
# 内存优化
# ------------------------------

CONFIG_MEMCG=y
CONFIG_MEMCG_SWAP=y
CONFIG_MEMCG_SWAP_ENABLED=y
CONFIG_MEMCG_KMEM=y
CONFIG_ZONE_DMA=y
CONFIG_ZONE_DMA32=y
CONFIG_ZONE_NORMAL=y
CONFIG_NUMA=y
CONFIG_SPARSEMEM=y
CONFIG_SPARSEMEM_VMEMMAP=y
CONFIG_HAVE_ARCH_PFN_VALID=y
CONFIG_PAGE_SHIFT=12
CONFIG_HIGHMEM64G=y
CONFIG_MOVABLE_NODE=y
CONFIG_COMPACTION=y
CONFIG_MIGRATION=y
CONFIG_PHYS_ADDR_T_64BIT=y
CONFIG_TRANSPARENT_HUGEPAGE=y
CONFIG_TRANSPARENT_HUGEPAGE_ALWAYS=y
CONFIG_TRANSPARENT_HUGEPAGE_MADVISE=y
CONFIG_TRANSPARENT_HUGE_PAGECACHE=y
CONFIG_CMA=y
CONFIG_CMA_DEBUGFS=y
CONFIG_CMA_SIZE_MBYTES=16
CONFIG_ZRAM=y
CONFIG_ZSMALLOC=y
CONFIG_ZSMALLOC_STAT=y
CONFIG_ZSWAP=y
CONFIG_ZSWAP_ZPOOL=y
CONFIG_ZSWAP_ZPOOL_ZBUD=y
CONFIG_ZSWAP_ZPOOL_ZSMALLOC=y
CONFIG_ZSWAP_ZPOOL_DEFAULT_ZBUD=y
CONFIG_ZSWAP_ZPOOL_DEFAULT_ZSMALLOC=y
CONFIG_ZSWAP_DEFAULT_ON=y
CONFIG_ZSWAP_COMPRESSOR_DEFAULT_LZ4=y

# ------------------------------
# 文件系统低功耗优化
# ------------------------------

CONFIG_EXT4_FS=y
CONFIG_EXT4_FS_POSIX_ACL=y
CONFIG_EXT4_FS_SECURITY=y
CONFIG_EXT4_FS_JBD2=y
CONFIG_FUSE_FS=y
CONFIG_OVERLAY_FS=y
CONFIG_SQUASHFS=y
CONFIG_SQUASHFS_ZLIB=y
CONFIG_SQUASHFS_LZ4=y
CONFIG_SQUASHFS_LZO=y
CONFIG_SQUASHFS_ZSTD=y
CONFIG_CIFS=y
CONFIG_NFS_FS=y
CONFIG_ISO9660_FS=y
CONFIG_VFAT_FS=y
CONFIG_NTFS_FS=y
CONFIG_NTFS_RW=y
CONFIG_TMPFS=y
CONFIG_TMPFS_POSIX_ACL=y
CONFIG_TMPFS_XATTR=y
CONFIG_HUGETLBFS=y
CONFIG_CONFIGFS_FS=y
CONFIG_DEVPTS_FS=y

# ------------------------------
# 多平台支持
# ------------------------------

CONFIG_BINFMT_MISC=y
CONFIG_BINFMT_ELF=y
CONFIG_MODULES=y
CONFIG_MODULE_UNLOAD=y
CONFIG_MODULE_FORCE_UNLOAD=y
CONFIG_MODVERSIONS=y
CONFIG_MODULE_COMPRESS=y
CONFIG_MODULE_COMPRESS_GZIP=y
CONFIG_MODULE_COMPRESS_LZ4=y
CONFIG_MODULE_COMPRESS_ZSTD=y

# ------------------------------
# 网络 (低功耗优化)
# ------------------------------

CONFIG_NET=y
CONFIG_PACKET=y
CONFIG_UNIX=y
CONFIG_INET=y
CONFIG_IPV6=y
CONFIG_INET_TCP_CONG_CUBIC=y
CONFIG_INET_TCP_CONG_BBR=y
CONFIG_TCP_CONG_ADVANCED=y
CONFIG_TCP_CONG_HTCP=y
CONFIG_TCP_CONG_VEGAS=y
CONFIG_TCP_CONG_YEAH=y
CONFIG_TCP_CONG_ILLINOIS=y
CONFIG_DEFAULT_CUBIC=y
CONFIG_DEFAULT_TCP_CONG="cubic"
CONFIG_CIFS=y
CONFIG_NFS_FS=y

# ------------------------------
# 设备驱动 (节能配置)
# ------------------------------

CONFIG_PCI=y
CONFIG_PCIE=y
CONFIG_PCIE_PME=y
CONFIG_PCIEASPM=y
CONFIG_PCIEASPM_DEFAULT=y
CONFIG_PCIEASPM_POWERSAVE=y
CONFIG_PCIEASPM_POWER_SUPERSAVE=y
CONFIG_PCIEASPM_PERFORMANCE=y

# ------------------------------
# 图形和显示
# ------------------------------

CONFIG_DRM=y
CONFIG_DRM_KMS_HELPER=y
CONFIG_DRM_FBDEV_EMULATION=y
CONFIG_DRM_I915=y
CONFIG_DRM_I915_FORCE_PROBE=""
CONFIG_DRM_I915_CAPTURE_ERROR=y
CONFIG_DRM_I915_COMPRESS_ERROR=y
CONFIG_DRM_I915_USERPTR=y
CONFIG_DRM_I915_GVT=y
CONFIG_DRM_I915_FENCE_TIMEOUT=10000
CONFIG_DRM_AMDGPU=y
CONFIG_FB=y
CONFIG_FB_EFI=y
CONFIG_FB_VESA=y

# ------------------------------
# 输入设备
# ------------------------------

CONFIG_INPUT=y
CONFIG_INPUT_KEYBOARD=y
CONFIG_KEYBOARD_ATKBD=y
CONFIG_INPUT_MOUSE=y
CONFIG_MOUSE_PS2=y
CONFIG_INPUT_TOUCHSCREEN=y

# ------------------------------
# 声音和音频
# ------------------------------

CONFIG_SOUND=y
CONFIG_SND=y
CONFIG_SND_TIMER=y
CONFIG_SND_PCM=y
CONFIG_SND_HWDEP=y
CONFIG_SND_JACK=y
CONFIG_SND_HDA_CORE=y
CONFIG_SND_HDA_INTEL=y
CONFIG_SND_HDA_DSP_LOADER=y
CONFIG_SND_HDA_EXT_CORE=y
CONFIG_SND_USB_AUDIO=y
CONFIG_SND_ALOOP=y
CONFIG_SND_VIRMIDI=y
CONFIG_SND_RAWMIDI=y
CONFIG_SND_SIMPLE_CARD=y

# ------------------------------
# USB
# ------------------------------

CONFIG_USB=y
CONFIG_USB_ANNOUNCE_NEW_DEVICES=y
CONFIG_USB_DEFAULT_PERSIST=y
CONFIG_USB_OTG=y
CONFIG_USB_OTG_BLACKLIST_HUB=y
CONFIG_USB_HOST=y
CONFIG_USB_PCI=y
CONFIG_USB_EHCI_HCD=y
CONFIG_USB_OHCI_HCD=y
CONFIG_USB_UHCI_HCD=y
CONFIG_USB_XHCI_HCD=y
CONFIG_USB_STORAGE=y

# ------------------------------
# 调试和诊断
# ------------------------------

CONFIG_DEBUG_KERNEL=y
CONFIG_DEBUG_INFO=y
CONFIG_MAGIC_SYSRQ=y
CONFIG_EARLY_PRINTK=y

# ------------------------------
# 64位 x86
# ------------------------------

CONFIG_64BIT=y
CONFIG_X86_64=y
CONFIG_SMP=y
CONFIG_NR_CPUS=512
CONFIG_PREEMPT=y
CONFIG_PREEMPT_VOLUNTARY=y
CONFIG_PREEMPT_NONE=y
CONFIG_RCU_EXPERT=y
CONFIG_RCU_BOOST=y
CONFIG_RCU_BOOST_DELAY=500
CONFIG_RCU_EQS=y

EOF

echo "✅ 已生成低功耗优化内核配置: $CONFIG_FILE"
echo "📋 核心优化："
echo "  - HZ=250 降低时钟频率"
echo "  - NO_HZ 动态计时"
echo "  - OnDemand 频率调节"
echo "  - 电源管理 (ACPI/CPUIdle)"
echo "  - 内存压缩 (ZRAM/ZSWAP)"
